[package]
name = "autosensitivity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Used for parsing command line argument
clap = { version = "4.0", features = ["derive"] }
home = "0.5.5"
